function showTips(msg){
	alert(msg);
//	 mini.showTips({
//        content: msg,
//        state: "danger",
//        x: "center",
//        y: "top",
//        timeout: 3000
//    });
}

/**
 * @Description: 获取url参数
 * @Param:  * @param name
 * @return:
 * @Author:	HeJiayan
 * @Date Create in 10:51 2018/5/23
 */
function getUrlParam(name) {
    var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)"); //构造一个含有目标参数的正则表达式对象
    var r = window.location.search.substr(1).match(reg); //匹配目标参数
    if (r != null)
        return unescape(getCharFromUtf8(r[2]));
    return null; //返回参数值
}

/**
 * @Description: 将URL中的UTF-8字符串转成中文字符串
 * @Param:  * @param str
 * @return:
 * @Author:	HeJiayan
 * @Date Create in 10:55 2018/5/23
 */
function getCharFromUtf8(str) {
    var cstr = "";
    var nOffset = 0;
    if (str == "")
        return "";
    str = str.toLowerCase();
    nOffset = str.indexOf("%e");
    if (nOffset == -1)
        return str;
    while (nOffset != -1) {
        cstr += str.substr(0, nOffset);
        str = str.substr(nOffset, str.length - nOffset);
        if (str == "" || str.length < 9)
            return cstr;
        cstr += utf8ToChar(str.substr(0, 9));
        str = str.substr(9, str.length - 9);
        nOffset = str.indexOf("%e");
    }
    return cstr + str;
}

/**
 * 错误检查
 * @param jsonMsg
 * @returns
 */
function errorCheck(jsonResult){
	try {
		var result = mini.decode(jsonResult);
		if (result.state == 0) {
			showTips(result.message);
			return false;
		}
		return true;
	} catch (e) {
		alert("解析发生错误！");
		return false;
	}
}
/**
 * 检查弹出确认框
 * @param jsonMsg
 * @returns
 */
function checkConfirm(jsonMsg){
	var result = mini.decode(jsonMsg);
	if (result.error_msg) {
		if(confirm("【"+result.error_msg+"】,是否继续？")){
			return true;
		}else{
			return false;
		}
	}
	return true;
}

//将“字符串”转换为“数字”
function stringToFloat(strPara){
	var strValue,decRtn;
	//对“传入参数”中的“非数字型特殊字符”进行处理
	strValue = String(strPara).replace(/,/g,"");
	decRtn = (isNaN(parseFloat(strValue)) ? 0 : parseFloat(strValue));
	return decRtn;
}

//将“字符串”转换为“整数字”
function stringToInt(strPara){
	var strValue;
	//对“传入参数”中的“非数字型特殊字符”进行处理
	strValue = String(strPara).replace(/,/g,"");
	var intRtn = (isNaN(parseInt(strValue)) ? 0 : parseInt(strValue));
	return intRtn;
}

/**
 * 把数字截取到精确度数位上(支持到万位)
 * @param {Object} a_num 需要截取的数据
 * @param {Object} a_str - 1(个位)、10(十位)、100(百位)、1000(千位)、10000(万位)
 */
function Truncate(a_num,a_str){
	a_str = String(a_str);
	if(a_str=="") return a_num;
	switch(a_str){
		case "1":
			return Math.floor(a_num);
			break;
		case "10":
			return Math.floor(a_num / 10) * 10;
			break;
		case "100":
			return Math.floor(a_num / 100) * 100;
			break;
		case "1000":
			return Math.floor(a_num / 1000) * 1000;
			break;
		case "10000":
			return Math.floor(a_num / 10000) * 10000;
			break;
		default :
			return a_num;
	}
}

// 根据保留位进行四舍五入
function Round(dec,decimals){
	if(isNaN(dec)) return 0;
	var step;
	var temp;
	dec = Math.round(dec * 100000000) / 100000000;
	if(dec == 0){
		return dec;
	}else{
		temp = Math.abs(dec);
		if(decimals == 0 || decimals == undefined){
			temp = Math.round(temp);	
		}else if(decimals>0){
			step = Math.pow(10,decimals);
			temp = Math.round(temp * step) / step;	
		}
		
		if(dec>0) {dec = temp;}
		else {dec = -temp;}
	}
	return dec;
}

/**
 * 代替原始的jqruy的ajax方法加入遮罩功能
 * 超时设置：如果没有设置超时：默认为10超时响应
 * obj 保留所有ajax中的设置
 * @param obj
 */
function Ajax(obj){
	$.ajax({
		type	: obj.type||"post",
		url 	: obj.url,
		data 	: obj.data,
		dataType: obj.dataType||"",
		timeout	: obj.timeout || "10000",
		beforeSend:function(){
			mini.mask({
	            el: document.body,
	            cls: 'mini-mask-loading',
	            html: obj.loadText||'加载中...'
	        });
		},
		complete:function(){
			mini.unmask(document.body);
		},
		success :function(msg){
			try{
				obj.success(msg);
			}catch(e){
				showTips(e.message);
			}
		},
		error :function(jqXHR, textStatus, errorThrown){
			if(textStatus=="timeout"){
				showTips("请求超时，请重试！如仍有问题请检查本地网络或与系统管理员联系！");
			}else{
				showTips("系统繁忙，请稍后再试！");
			}
		}
	});
};

/**
 * 空字符串转换
 * @param obj
 */
function empty(obj){
	if(obj == null || obj == "null" || typeof(obj)=="undefined" || $.trim(obj)==""){
		return "";
	}
	return obj;
}

/**
 * miniForm数据包装
 * @param {Object} formId - 表单id
 */
function serializeArray(formId){
	var form = new mini.Form(formId);
	var data = [];
	var fields = form.getFields();
	for (var i = 0; i < fields.length; i++) {
		var field = fields[i];
		var name = field.getName();
		if(empty(name) == "")continue;
		var value = field.getValue();
		if($(field.getEl()).hasClass("mini-currency")){
			value =  reThousandFormat(value);
		}else if(field.type == "datepicker"){
			var format = field.format || "yyyy-MM-dd";
			value = mini.formatDate (value, format);
		}else if(field.type == "monthpicker"){
			var format = field.format || "yyyy-MM";
			value = mini.formatDate (value, format);
		}
		data.push({name: name, value: empty(value)});
	}
	return data;
}

function arrayToObject(data){
	var o={};
    $.each(data, function () {
        if (o[this.name]) {
            if (!o[this.name].push) {
                o[this.name] = [o[this.name]];
            }
            o[this.name].push(this.value || '');
        } else {
            o[this.name] = this.value || '';
        }
    });
    return o;
}

/**
 * 普通Form数据包装(form表单包含非mini控件且控件name不允许重复)
 * @param {Object} formId - 表单id
 */
function serializeArrayNormal(formId){
	var form = new mini.Form(formId);
	var data = $("#"+formId+" :input[name]").serializeArray();
	var fields = form.getFields();
	for (var i = 0; i < fields.length; i++) {
		var field = fields[i];
		var name = field.getName();
		var value = field.getValue();
		if($(field.getEl()).hasClass("mini-currency")){
			for(var j = 0; j < data.length; j++){
				if(data[j].name == name){
					data[j].value = reThousandFormat(empty(value));
				}
			}
		}
	}
	return data;
}

/**
 * 设置表单显示模式
 * @param {Object} formId - 表单id
 * @param {Object} viewMode - (true|false)是否查看模式
 */
function showViewModel(formId, viewMode) {
	var form = new mini.Form(formId);
    var fields = form.getFields(); 
    if(viewMode){
    	for (var i = 0; i < fields.length;i++) {
    		var field = fields[i];
    		if(field.type == "hidden") continue;
    		var el = field.getEl();
    		var value =  field.getText ? field.getText() : field.getValue();
    		if(field.type == "radiobuttonlist" && value){
    			value = field.getItemText(field.getItem(value));
    		}
    		if(value){
    			value = value.replace(/\n/g, "<br>");
			}
    		var label = "<div class='_label _label_"+ field.name +"' style='text-align:inherit; white-space:normal;width:100%;padding-left:2px'>" + value + "</div>";
    		$(el).siblings("._label").remove();
    		$(el).hide().before(label);
        }
		$("#"+formId).find("a:not(.fixed)").hide();
		$(".mini-pager .mini-button").show();//分页组件需显示
		$("#"+formId).find(".uploadify").hide();//上传组件
    }else{
    	for (var i = 0; i < fields.length;i++) {
    		var field = fields[i];
    		if(field.type == "hidden") continue;
    		var el = field.getEl();
    		$(el).siblings("._label").remove();
    		$(el).show();
        }
		$("#"+formId).find("a:not(.fixed)").show();
		$("#"+formId).find(".uploadify").show();//上传组件
    }
}

/**
 * @param {Object} formId
 */
function disableForm(formId){
	var form = new mini.Form(formId);
	var fields = form.getFields();                
    for (var i = 0, l = fields.length; i < l; i++) {
        var c = fields[i];
        if (c.setReadOnly) c.setReadOnly(true);     //只读
        if (c.setIsValid) c.setIsValid(true);      //去除错误提示
        if (c.addCls) c.addCls("asLabel");          //增加asLabel外观
        c.setEnabled(false);
    }
	//按钮不可见
	$("#"+formId).find("a:not(.fixed)").hide();
	//上传组件隐藏
	$("#"+formId).find(".uploadify").hide();
}

/**
 * 添加千位符，并保留precision位小数(默认为2位)
 * s字符型金额
 */
function thousandFormat(s,precision){
	if(isNaN(precision)) precision = 2;
	s = reThousandFormat(s);
	if(empty(s) == "") return new Number(0).toFixed(precision);
	 if(isNaN(s)){
    	alert("无效数字");
    	return new Number(0).toFixed(precision);  
    }
	//正式处理
	var sign = (s < 0) ? '-' : '';
	var i = parseInt(s = Math.abs(s).toFixed(precision)) + "";
	var j = (j = i.length) > 3 ? j % 3 : 0;
	return sign + (j ? i.substr(0, j) + "," : "") + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1,") + (precision ? "." + Math.abs(s - i).toFixed(precision).slice(2) : "");
} 

/**
 * 还原千位符的数字
 * s字符型金额
 */
function reThousandFormat(s){
	if(empty(s)=="") return "";
	return new String(s).replace(/,/g, "");
} 

function decodeToJson(jsonSting){
	try{
		return mini.decode(jsonSting.replace(/\r/g,'\\r').replace(/\n/g,'\\n').replace(/\t/g,'\\t'));
	}catch(e){
		showTips("数据加载错误，请与管理员联系！");
		return "";
	}
}

/**
 * 填充表单数据
 * @param {Object} formId - 表单id
 * @param {Object} data - 填充数据Json数据
 * @param {Object} notDefaultFill - 如果填充数据为空是否进行默认填充,默认为默认填充
 */
function setFormData(formId,data,notDefaultFill){
	var form = new mini.Form(formId);
	form.setData(data);
	var fields = form.getFields();
	for (var i = 0; i < fields.length; i++) {
		var field = fields[i];
		var value = field.getValue();
		if($(field.getEl()).hasClass("mini-currency")){
			field.setValue(thousandFormat(value||"0"));
		}else if(field.type == "radiobuttonlist" && !notDefaultFill){
			field.setValue(value||field.defaultValue);
		}else if(!value && field.defaultValue && !notDefaultFill){
			field.setValue(value||field.defaultValue);
			if (field.type == "buttonedit") {
				field.setText(field.defaultText);
			}
		}
	}
}

/**
 * 部门、岗位、用户通用选择
 * @param {Object} control_name - mini-buttonedit控件,用于设置no和name
 * @param {Object} type_el_name - mini-hidden控件,用于设置对象类型
 * @param {Object} callback - 回调函数
 * @param {Object} flag - 选择类型标志(默认值111) : 111-部门岗位人员, 100-部门, 010-岗位, 011-岗位人员， 001 人员
 * @param {Object} multiSelect - 是否多选(默认值true)
 */
function selectAddress(control_name, type_el_name, flag, multiSelect, callback){
	var btnEdit = (typeof(control_name)==="object")? control_name : mini.getbyName(control_name);
	var type_el = type_el_name ? mini.getbyName(type_el_name) : null;
	var callback = callback || function(){};
	var flag = flag || "111";
	var multiSelect = (multiSelect === false)? false : true;
	mini.open({
        url: "addressbook?multiSelect="+ multiSelect +"&flag="+ flag,
        title: "地址本",
        width: 800,
        height: 600,
		onload:function(){
			var iframe = this.getIFrameEl();
			if(type_el){
				iframe.contentWindow.SetData({object_ids:btnEdit.getValue(), object_names:btnEdit.getText(), object_types:type_el.getValue()});
			}else{
				iframe.contentWindow.SetData({object_ids:btnEdit.getValue(), object_names:btnEdit.getText()});
			}
		},
        ondestroy: function (action) {
			if (action == "ok") {
                var iframe = this.getIFrameEl();
                var data = iframe.contentWindow.GetData();
                data = mini.clone(data);    //必须
                if (data) {
                    var ids = [], names = [], types = [];
					for(var i = 0; i < data.length; i++){
						ids.push(data[i].object_id);
						names.push(data[i].object_name);
						if(type_el){
							types.push(data[i].object_type);
						}
					}
					btnEdit.setValue(ids.join(","));
					btnEdit.setText(names.join(","));
					if(type_el){
						type_el.setValue(types.join(","));
					}
					//回调函数
					if(multiSelect){
						callback(data);
					}else{
						callback(data[0]);
					}
                }
            }
        }
    });
}

/**
 * 选择用户(单选)
 * @see - selectAddress(control_name, type_el_name, flag, multiSelect, callback)
 * @param {Object} e - mini.ButtonEdit控件点击事件
 * @param {Object} callback - 回调函数
 */
function selectUser(e, callback){
	var btnEdit = e.sender;
	selectAddress(btnEdit, null, "001", false, callback);
}

/**
 * 选择用户(多选)
 * @param {Object} e
 * @param {Object} callback
 */
function selectUserMulti(e, callback){
	var btnEdit = e.sender;
	selectAddress(btnEdit, null, "001", true, callback);
}

/**
 * 选择岗位(单选)
 * @param {Object} e - mini.ButtonEdit控件点击事件
 * @param {Object} callback - 回调函数
 */
function selectPosi(e, callback){
	var btnEdit = e.sender;
	selectAddress(btnEdit, null, "010", false, callback);
}

/**
 * 选择岗位(多选)
 * @param {Object} e
 * @param {Object} callback
 */
function selectPosiMulti(e, callback){
	var btnEdit = e.sender;
	selectAddress(btnEdit, null, "010", true, callback);
}

/**
 * 选择部门(单选)
 * @param {Object} e - mini.ButtonEdit控件点击事件
 * @param {Object} callback - 回调函数
 */
function selectDept(e, callback){
	var btnEdit = e.sender;
	selectAddress(btnEdit, null, "100", false, callback);
}

/**
 * 选择部门(多选)
 * @param {Object} e - mini.ButtonEdit控件点击事件
 * @param {Object} callback - 回调函数
 */
function selectDeptMulti(e, callback){
	var btnEdit = e.sender;
	selectAddress(btnEdit, null, "100", true, callback);
}

/**
 * 根据保留位(元、角、分)获取数字形式的保留位(0、1、2)
 * @param {Object} keep_pos
 */
function getKeepPos(keep_pos){
	switch(keep_pos){
		case "Y"://元
			return 0;
			break;
		case "J"://角
			return 1;
			break;
		case "F"://分
			return 2;
			break;
		default:
			return 2;
			break;
	}
}

/**
 * 金额大写转换
 * @param {Object} num
 */
function toUpperAmount(num){ //转成人民币大写金额形式 
	  var str1 = '零壹贰叁肆伍陆柒捌玖';  //0-9所对应的汉字 
	  var str2 = '万仟佰拾亿仟佰拾万仟佰拾元角分'; //数字位所对应的汉字 
	  var str3;    //从原num值中取出的值 
	  var str4;    //数字的字符串形式 
	  var str5 = '';  //人民币大写金额形式 
	  var i;    //循环变量 
	  var j;    //num的值乘以100的字符串长度 
	  var ch1;    //数字的汉语读法 
	  var ch2;    //数字位的汉字读法 
	  var nzero = 0;  //用来计算连续的零值是几个 
	  num = Math.abs(num).toFixed(2);  //将num取绝对值并四舍五入取2位小数 
	  str4 = (num * 100).toFixed(0).toString();  //将num乘100并转换成字符串形式 
	  j = str4.length;      //找出最高位 
	  if (j > 15){return '溢出';} 
	  str2 = str2.substr(15-j);    //取出对应位数的str2的值。如：200.55,j为5所以str2=佰拾元角分 
  	  //循环取出每一位需要转换的值 
	  for(i=0;i<j;i++){
		    str3 = str4.substr(i,1);   //取出需转换的某一位的值 
		    if(i != (j-3) && i != (j-7) && i != (j-11) && i != (j-15)){//当所取位数不为元、万、亿、万亿上的数字时 
			   if(str3 == '0'){
			     ch1 = ''; 
			     ch2 = ''; 
			  	 nzero = nzero + 1; 
			   }else{
			     if(str3 != '0' && nzero != 0){ 
			       ch1 = '零' + str1.substr(str3*1,1); 
			          ch2 = str2.substr(i,1); 
			          nzero = 0; 
			  }else{
			    ch1 = str1.substr(str3*1,1); 
			          ch2 = str2.substr(i,1); 
			          nzero = 0; 
			    }
			  }
		   }else{ //该位是万亿，亿，万，元位等关键位 
		      if (str3 != '0' && nzero != 0){ 
		        ch1 = "零" + str1.substr(str3*1,1); 
		        ch2 = str2.substr(i,1); 
		        nzero = 0; 
		      }else{ 
		     	if(str3 != '0' && nzero == 0){ 
		          ch1 = str1.substr(str3*1,1); 
		          ch2 = str2.substr(i,1); 
		          nzero = 0; 
		  		}else{ 
			    	if (str3 == '0' && nzero >= 3){
			            ch1 = ''; 
			            ch2 = ''; 
			            nzero = nzero + 1; 
			        }else{
				      if (j >= 11){ 
			            ch1 = ''; 
			            nzero = nzero + 1; 
				   	}else{ 
					    ch1 = ''; 
					    ch2 = str2.substr(i,1); 
					    nzero = nzero + 1; 
				    } 
		          } 
		  	    } 
		   	 } 
		  } 
		  if (i == (j-11) || i == (j-3)){  //如果该位是亿位或元位，则必须写上 
		      ch2 = str2.substr(i,1); 
		  } 
		  str5 = str5 + ch1 + ch2; 
		  if (i == j-1 && str3 == '0'){   //最后一位（分）为0时，加上“整” 
		      str5 = str5 + '整'; 
		  } 
	 } 
	 if (num == 0){ 
	   str5 = '零元整'; 
	 } 
  return str5;  
} 

/**
 * datagrid的全选与反选
 */
/**
 * datagrid的全选与反选
 * @param {Object} thisObj - this对象
 * @param {Object} datagrid_id - datagrid对象ID
 */
function checkAll(thisObj,datagrid_id){
	var gridObj=mini.get(datagrid_id);
	if(gridObj.enabled){
		if(thisObj.checked){
			gridObj.selectAll();
		}else{
			gridObj.deselectAll();
		}
	}
}

//选择项目
function selectPrj(e){
	var btnEdit = e.sender;
	mini.open({
        url: "plan/nodeYieldRate/common_selectPrj",
        title: "项目列表",
        width: 300,
        height: 460,
        ondestroy: function (action) {
        	 if (action == "ok") {
                var iframe = this.getIFrameEl();
                var data = iframe.contentWindow.GetData();
                data = mini.clone(data);    //必须
                if (data.length != 0 && data) {
					var ids = [], names = [];
					for(var i = 0; i < data.length; i++){
						ids.push(data[i].prj_id);
						names.push(data[i].prj_short_name);
					}
					btnEdit.setValue(ids.join(","));
					btnEdit.setText(names.join(","));
					getChartData();
                }
            } 
        }
    });		
}

//事件处理------------------------------------------
$(function(){
	$(".mini-currency").each(function(){
		var el = $(this);
		if(el.is("span")){
			var elName = el.find("input[name]").attr("name");
			var miniEl = mini.getbyName(elName);
			if(miniEl){
				miniEl.on("valuechanged",function(){
					miniEl.setValue(thousandFormat(miniEl.getValue()));
				});
			}
		}
	});
	
	/**
	 * 如果是银行帐号，则四位隔开
	 */
	$(".mini-bank-no").each(function(){
		var el = $(this);
		if(el.is("span")){
			var elName = el.find("input[name]").attr("name");
			var miniEl = mini.getbyName(elName);
			if(miniEl){
				miniEl.on("valuechanged",function(){
					miniEl.setValue(miniEl.getValue().replace(/(\d{4})(?=\d)/g, "$1 "));
				});
			}
		}
	});
});

function handleSubject(item){
	item=item.replace("#","*-001-*");
	item=item.replace("!","*-002-*");
	item=item.replace("?","*-003-*");
	item=item.replace("！","*-002-*");
	item=item.replace("？","*-003-*");
	item=item.replace("&","*-004-*");
	return item;
}

//--------获取输入项的拼音首字母--------
var strChineseFirstPY = "YDYQSXMWZSSXJBYMGCCZQPSSQBYCDSCDQLDYLYBSSJGYZZJJFKCCLZDHWDWZJLJPFYYNWJJTMYHZWZHFLZPPQHGSCYYYNJQYXXGJHHSDSJNKKTMOMLCRXYPSNQSECCQZGGLLYJLMYZZSECYKYYHQWJSSGGYXYZYJWWKDJHYCHMYXJTLXJYQBYXZLDWRDJRWYSRLDZJPCBZJJBRCFTLECZSTZFXXZHTRQHYBDLYCZSSYMMRFMYQZPWWJJYFCRWFDFZQPYDDWYXKYJAWJFFXYPSFTZYHHYZYSWCJYXSCLCXXWZZXNBGNNXBXLZSZSBSGPYSYZDHMDZBQBZCWDZZYYTZHBTSYYBZGNTNXQYWQSKBPHHLXGYBFMJEBJHHGQTJCYSXSTKZHLYCKGLYSMZXYALMELDCCXGZYRJXSDLTYZCQKCNNJWHJTZZCQLJSTSTBNXBTYXCEQXGKWJYFLZQLYHYXSPSFXLMPBYSXXXYDJCZYLLLSJXFHJXPJBTFFYABYXBHZZBJYZLWLCZGGBTSSMDTJZXPTHYQTGLJSCQFZKJZJQNLZWLSLHDZBWJNCJZYZSQQYCQYRZCJJWYBRTWPYFTWEXCSKDZCTBZHYZZYYJXZCFFZZMJYXXSDZZOTTBZLQWFCKSZSXFYRLNYJMBDTHJXSQQCCSBXYYTSYFBXDZTGBCNSLCYZZPSAZYZZSCJCSHZQYDXLBPJLLMQXTYDZXSQJTZPXLCGLQTZWJBHCTSYJSFXYEJJTLBGXSXJMYJQQPFZASYJNTYDJXKJCDJSZCBARTDCLYJQMWNQNCLLLKBYBZZSYHQQLTWLCCXTXLLZNTYLNEWYZYXCZXXGRKRMTCNDNJTSYYSSDQDGHSDBJGHRWRQLYBGLXHLGTGXBQJDZPYJSJYJCTMRNYMGRZJCZGJMZMGXMPRYXKJNYMSGMZJYMKMFXMLDTGFBHCJHKYLPFMDXLQJJSMTQGZSJLQDLDGJYCALCMZCSDJLLNXDJFFFFJCZFMZFFPFKHKGDPSXKTACJDHHZDDCRRCFQYJKQCCWJDXHWJLYLLZGCFCQDSMLZPBJJPLSBCJGGDCKKDEZSQCCKJGCGKDJTJDLZYCXKLQSCGJCLTFPCQCZGWPJDQYZJJBYJHSJDZWGFSJGZKQCCZLLPSPKJGQJHZZLJPLGJGJJTHJJYJZCZMLZLYQBGJWMLJKXZDZNJQSYZMLJLLJKYWXMKJLHSKJGBMCLYYMKXJQLBMLLKMDXXKWYXYSLMLPSJQQJQXYXFJTJDXMXXLLCXQBSYJBGWYMBGGBCYXPJYGPEPFGDJGBHBNSQJYZJKJKHXQFGQZKFHYGKHDKLLSDJQXPQYKYBNQSXQNSZSWHBSXWHXWBZZXDMNSJBSBKBBZKLYLXGWXDRWYQZMYWSJQLCJXXJXKJEQXSCYETLZHLYYYSDZPAQYZCMTLSHTZCFYZYXYLJSDCJQAGYSLCQLYYYSHMRQQKLDXZSCSSSYDYCJYSFSJBFRSSZQSBXXPXJYSDRCKGJLGDKZJZBDKTCSYQPYHSTCLDJDHMXMCGXYZHJDDTMHLTXZXYLYMOHYJCLTYFBQQXPFBDFHHTKSQHZYYWCNXXCRWHOWGYJLEGWDQCWGFJYCSNTMYTOLBYGWQWESJPWNMLRYDZSZTXYQPZGCWXHNGPYXSHMYQJXZTDPPBFYHZHTJYFDZWKGKZBLDNTSXHQEEGZZYLZMMZYJZGXZXKHKSTXNXXWYLYAPSTHXDWHZYMPXAGKYDXBHNHXKDPJNMYHYLPMGOCSLNZHKXXLPZZLBMLSFBHHGYGYYGGBHSCYAQTYWLXTZQCEZYDQDQMMHTKLLSZHLSJZWFYHQSWSCWLQAZYNYTLSXTHAZNKZZSZZLAXXZWWCTGQQTDDYZTCCHYQZFLXPSLZYGPZSZNGLNDQTBDLXGTCTAJDKYWNSYZLJHHZZCWNYYZYWMHYCHHYXHJKZWSXHZYXLYSKQYSPSLYZWMYPPKBYGLKZHTYXAXQSYSHXASMCHKDSCRSWJPWXSGZJLWWSCHSJHSQNHCSEGNDAQTBAALZZMSSTDQJCJKTSCJAXPLGGXHHGXXZCXPDMMHLDGTYBYSJMXHMRCPXXJZCKZXSHMLQXXTTHXWZFKHCCZDYTCJYXQHLXDHYPJQXYLSYYDZOZJNYXQEZYSQYAYXWYPDGXDDXSPPYZNDLTWRHXYDXZZJHTCXMCZLHPYYYYMHZLLHNXMYLLLMDCPPXHMXDKYCYRDLTXJCHHZZXZLCCLYLNZSHZJZZLNNRLWHYQSNJHXYNTTTKYJPYCHHYEGKCTTWLGQRLGGTGTYGYHPYHYLQYQGCWYQKPYYYTTTTLHYHLLTYTTSPLKYZXGZWGPYDSSZZDQXSKCQNMJJZZBXYQMJRTFFBTKHZKBXLJJKDXJTLBWFZPPTKQTZTGPDGNTPJYFALQMKGXBDCLZFHZCLLLLADPMXDJHLCCLGYHDZFGYDDGCYYFGYDXKSSEBDHYKDKDKHNAXXYBPBYYHXZQGAFFQYJXDMLJCSQZLLPCHBSXGJYNDYBYQSPZWJLZKSDDTACTBXZDYZYPJZQSJNKKTKNJDJGYYPGTLFYQKASDNTCYHBLWDZHBBYDWJRYGKZYHEYYFJMSDTYFZJJHGCXPLXHLDWXXJKYTCYKSSSMTWCTTQZLPBSZDZWZXGZAGYKTYWXLHLSPBCLLOQMMZSSLCMBJCSZZKYDCZJGQQDSMCYTZQQLWZQZXSSFPTTFQMDDZDSHDTDWFHTDYZJYQJQKYPBDJYYXTLJHDRQXXXHAYDHRJLKLYTWHLLRLLRCXYLBWSRSZZSYMKZZHHKYHXKSMDSYDYCJPBZBSQLFCXXXNXKXWYWSDZYQOGGQMMYHCDZTTFJYYBGSTTTYBYKJDHKYXBELHTYPJQNFXFDYKZHQKZBYJTZBXHFDXKDASWTAWAJLDYJSFHBLDNNTNQJTJNCHXFJSRFWHZFMDRYJYJWZPDJKZYJYMPCYZNYNXFBYTFYFWYGDBNZZZDNYTXZEMMQBSQEHXFZMBMFLZZSRXYMJGSXWZJSPRYDJSJGXHJJGLJJYNZZJXHGXKYMLPYYYCXYTWQZSWHWLYRJLPXSLSXMFSWWKLCTNXNYNPSJSZHDZEPTXMYYWXYYSYWLXJQZQXZDCLEEELMCPJPCLWBXSQHFWWTFFJTNQJHJQDXHWLBYZNFJLALKYYJLDXHHYCSTYYWNRJYXYWTRMDRQHWQCMFJDYZMHMYYXJWMYZQZXTLMRSPWWCHAQBXYGZYPXYYRRCLMPYMGKSJSZYSRMYJSNXTPLNBAPPYPYLXYYZKYNLDZYJZCZNNLMZHHARQMPGWQTZMXXMLLHGDZXYHXKYXYCJMFFYYHJFSBSSQLXXNDYCANNMTCJCYPRRNYTYQNYYMBMSXNDLYLYSLJRLXYSXQMLLYZLZJJJKYZZCSFBZXXMSTBJGNXYZHLXNMCWSCYZYFZLXBRNNNYLBNRTGZQYSATSWRYHYJZMZDHZGZDWYBSSCSKXSYHYTXXGCQGXZZSHYXJSCRHMKKBXCZJYJYMKQHZJFNBHMQHYSNJNZYBKNQMCLGQHWLZNZSWXKHLJHYYBQLBFCDSXDLDSPFZPSKJYZWZXZDDXJSMMEGJSCSSMGCLXXKYYYLNYPWWWGYDKZJGGGZGGSYCKNJWNJPCXBJJTQTJWDSSPJXZXNZXUMELPXFSXTLLXCLJXJJLJZXCTPSWXLYDHLYQRWHSYCSQYYBYAYWJJJQFWQCQQCJQGXALDBZZYJGKGXPLTZYFXJLTPADKYQHPMATLCPDCKBMTXYBHKLENXDLEEGQDYMSAWHZMLJTWYGXLYQZLJEEYYBQQFFNLYXRDSCTGJGXYYNKLLYQKCCTLHJLQMKKZGCYYGLLLJDZGYDHZWXPYSJBZKDZGYZZHYWYFQYTYZSZYEZZLYMHJJHTSMQWYZLKYYWZCSRKQYTLTDXWCTYJKLWSQZWBDCQYNCJSRSZJLKCDCDTLZZZACQQZZDDXYPLXZBQJYLZLLLQDDZQJYJYJZYXNYYYNYJXKXDAZWYRDLJYYYRJLXLLDYXJCYWYWNQCCLDDNYYYNYCKCZHXXCCLGZQJGKWPPCQQJYSBZZXYJSQPXJPZBSBDSFNSFPZXHDWZTDWPPTFLZZBZDMYYPQJRSDZSQZSQXBDGCPZSWDWCSQZGMDHZXMWWFYBPDGPHTMJTHZSMMBGZMBZJCFZWFZBBZMQCFMBDMCJXLGPNJBBXGYHYYJGPTZGZMQBQTCGYXJXLWZKYDPDYMGCFTPFXYZTZXDZXTGKMTYBBCLBJASKYTSSQYYMSZXFJEWLXLLSZBQJJJAKLYLXLYCCTSXMCWFKKKBSXLLLLJYXTYLTJYYTDPJHNHNNKBYQNFQYYZBYYESSESSGDYHFHWTCJBSDZZTFDMXHCNJZYMQWSRYJDZJQPDQBBSTJGGFBKJBXTGQHNGWJXJGDLLTHZHHYYYYYYSXWTYYYCCBDBPYPZYCCZYJPZYWCBDLFWZCWJDXXHYHLHWZZXJTCZLCDPXUJCZZZLYXJJTXPHFXWPYWXZPTDZZBDZCYHJHMLXBQXSBYLRDTGJRRCTTTHYTCZWMXFYTWWZCWJWXJYWCSKYBZSCCTZQNHXNWXXKHKFHTSWOCCJYBCMPZZYKBNNZPBZHHZDLSYDDYTYFJPXYNGFXBYQXCBHXCPSXTYZDMKYSNXSXLHKMZXLYHDHKWHXXSSKQYHHCJYXGLHZXCSNHEKDTGZXQYPKDHEXTYKCNYMYYYPKQYYYKXZLTHJQTBYQHXBMYHSQCKWWYLLHCYYLNNEQXQWMCFBDCCMLJGGXDQKTLXKGNQCDGZJWYJJLYHHQTTTNWCHMXCXWHWSZJYDJCCDBQCDGDNYXZTHCQRXCBHZTQCBXWGQWYYBXHMBYMYQTYEXMQKYAQYRGYZSLFYKKQHYSSQYSHJGJCNXKZYCXSBXYXHYYLSTYCXQTHYSMGSCPMMGCCCCCMTZTASMGQZJHKLOSQYLSWTMXSYQKDZLJQQYPLSYCZTCQQPBBQJZCLPKHQZYYXXDTDDTSJCXFFLLCHQXMJLWCJCXTSPYCXNDTJSHJWXDQQJSKXYAMYLSJHMLALYKXCYYDMNMDQMXMCZNNCYBZKKYFLMCHCMLHXRCJJHSYLNMTJZGZGYWJXSRXCWJGJQHQZDQJDCJJZKJKGDZQGJJYJYLXZXXCDQHHHEYTMHLFSBDJSYYSHFYSTCZQLPBDRFRZTZYKYWHSZYQKWDQZRKMSYNBCRXQBJYFAZPZZEDZCJYWBCJWHYJBQSZYWRYSZPTDKZPFPBNZTKLQYHBBZPNPPTYZZYBQNYDCPJMMCYCQMCYFZZDCMNLFPBPLNGQJTBTTNJZPZBBZNJKLJQYLNBZQHKSJZNGGQSZZKYXSHPZSNBCGZKDDZQANZHJKDRTLZLSWJLJZLYWTJNDJZJHXYAYNCBGTZCSSQMNJPJYTYSWXZFKWJQTKHTZPLBHSNJZSYZBWZZZZLSYLSBJHDWWQPSLMMFBJDWAQYZTCJTBNNWZXQXCDSLQGDSDPDZHJTQQPSWLYYJZLGYXYZLCTCBJTKTYCZJTQKBSJLGMGZDMCSGPYNJZYQYYKNXRPWSZXMTNCSZZYXYBYHYZAXYWQCJTLLCKJJTJHGDXDXYQYZZBYWDLWQCGLZGJGQRQZCZSSBCRPCSKYDZNXJSQGXSSJMYDNSTZTPBDLTKZWXQWQTZEXNQCZGWEZKSSBYBRTSSSLCCGBPSZQSZLCCGLLLZXHZQTHCZMQGYZQZNMCOCSZJMMZSQPJYGQLJYJPPLDXRGZYXCCSXHSHGTZNLZWZKJCXTCFCJXLBMQBCZZWPQDNHXLJCTHYZLGYLNLSZZPCXDSCQQHJQKSXZPBAJYEMSMJTZDXLCJYRYYNWJBNGZZTMJXLTBSLYRZPYLSSCNXPHLLHYLLQQZQLXYMRSYCXZLMMCZLTZSDWTJJLLNZGGQXPFSKYGYGHBFZPDKMWGHCXMSGDXJMCJZDYCABXJDLNBCDQYGSKYDQTXDJJYXMSZQAZDZFSLQXYJSJZYLBTXXWXQQZBJZUFBBLYLWDSLJHXJYZJWTDJCZFQZQZZDZSXZZQLZCDZFJHYSPYMPQZMLPPLFFXJJNZZYLSJEYQZFPFZKSYWJJJHRDJZZXTXXGLGHYDXCSKYSWMMZCWYBAZBJKSHFHJCXMHFQHYXXYZFTSJYZFXYXPZLCHMZMBXHZZSXYFYMNCWDABAZLXKTCSHHXKXJJZJSTHYGXSXYYHHHJWXKZXSSBZZWHHHCWTZZZPJXSNXQQJGZYZYWLLCWXZFXXYXYHXMKYYSWSQMNLNAYCYSPMJKHWCQHYLAJJMZXHMMCNZHBHXCLXTJPLTXYJHDYYLTTXFSZHYXXSJBJYAYRSMXYPLCKDUYHLXRLNLLSTYZYYQYGYHHSCCSMZCTZQXKYQFPYYRPFFLKQUNTSZLLZMWWTCQQYZWTLLMLMPWMBZSSTZRBPDDTLQJJBXZCSRZQQYGWCSXFWZLXCCRSZDZMCYGGDZQSGTJSWLJMYMMZYHFBJDGYXCCPSHXNZCSBSJYJGJMPPWAFFYFNXHYZXZYLREMZGZCYZSSZDLLJCSQFNXZKPTXZGXJJGFMYYYSNBTYLBNLHPFZDCYFBMGQRRSSSZXYSGTZRNYDZZCDGPJAFJFZKNZBLCZSZPSGCYCJSZLMLRSZBZZLDLSLLYSXSQZQLYXZLSKKBRXBRBZCYCXZZZEEYFGKLZLYYHGZSGZLFJHGTGWKRAAJYZKZQTSSHJJXDCYZUYJLZYRZDQQHGJZXSSZBYKJPBFRTJXLLFQWJHYLQTYMBLPZDXTZYGBDHZZRBGXHWNJTJXLKSCFSMWLSDQYSJTXKZSCFWJLBXFTZLLJZLLQBLSQMQQCGCZFPBPHZCZJLPYYGGDTGWDCFCZQYYYQYSSCLXZSKLZZZGFFCQNWGLHQYZJJCZLQZZYJPJZZBPDCCMHJGXDQDGDLZQMFGPSYTSDYFWWDJZJYSXYYCZCYHZWPBYKXRYLYBHKJKSFXTZJMMCKHLLTNYYMSYXYZPYJQYCSYCWMTJJKQYRHLLQXPSGTLYYCLJSCPXJYZFNMLRGJJTYZBXYZMSJYJHHFZQMSYXRSZCWTLRTQZSSTKXGQKGSPTGCZNJSJCQCXHMXGGZTQYDJKZDLBZSXJLHYQGGGTHQSZPYHJHHGYYGKGGCWJZZYLCZLXQSFTGZSLLLMLJSKCTBLLZZSZMMNYTPZSXQHJCJYQXYZXZQZCPSHKZZYSXCDFGMWQRLLQXRFZTLYSTCTMJCXJJXHJNXTNRZTZFQYHQGLLGCXSZSJDJLJCYDSJTLNYXHSZXCGJZYQPYLFHDJSBPCCZHJJJQZJQDYBSSLLCMYTTMQTBHJQNNYGKYRQYQMZGCJKPDCGMYZHQLLSLLCLMHOLZGDYYFZSLJCQZLYLZQJESHNYLLJXGJXLYSYYYXNBZLJSSZCQQCJYLLZLTJYLLZLLBNYLGQCHXYYXOXCXQKYJXXXYKLXSXXYQXCYKQXQCSGYXXYQXYGYTQOHXHXPYXXXULCYEYCHZZCBWQBBWJQZSCSZSSLZYLKDESJZWMYMCYTSDSXXSCJPQQSQYLYYZYCMDJDZYWCBTJSYDJKCYDDJLBDJJSODZYSYXQQYXDHHGQQYQHDYXWGMMMAJDYBBBPPBCMUUPLJZSMTXERXJMHQNUTPJDCBSSMSSSTKJTSSMMTRCPLZSZMLQDSDMJMQPNQDXCFYNBFSDQXYXHYAYKQYDDLQYYYSSZBYDSLNTFQTZQPZMCHDHCZCWFDXTMYQSPHQYYXSRGJCWTJTZZQMGWJJTJHTQJBBHWZPXXHYQFXXQYWYYHYSCDYDHHQMNMTMWCPBSZPPZZGLMZFOLLCFWHMMSJZTTDHZZYFFYTZZGZYSKYJXQYJZQBHMBZZLYGHGFMSHPZFZSNCLPBQSNJXZSLXXFPMTYJYGBXLLDLXPZJYZJYHHZCYWHJYLSJEXFSZZYWXKZJLUYDTMLYMQJPWXYHXSKTQJEZRPXXZHHMHWQPWQLYJJQJJZSZCPHJLCHHNXJLQWZJHBMZYXBDHHYPZLHLHLGFWLCHYYTLHJXCJMSCPXSTKPNHQXSRTYXXTESYJCTLSSLSTDLLLWWYHDHRJZSFGXTSYCZYNYHTDHWJSLHTZDQDJZXXQHGYLTZPHCSQFCLNJTCLZPFSTPDYNYLGMJLLYCQHYSSHCHYLHQYQTMZYPBYWRFQYKQSYSLZDQJMPXYYSSRHZJNYWTQDFZBWWTWWRXCWHGYHXMKMYYYQMSMZHNGCEPMLQQMTCWCTMMPXJPJJHFXYYZSXZHTYBMSTSYJTTQQQYYLHYNPYQZLCYZHZWSMYLKFJXLWGXYPJYTYSYXYMZCKTTWLKSMZSYLMPWLZWXWQZSSAQSYXYRHSSNTSRAPXCPWCMGDXHXZDZYFJHGZTTSBJHGYZSZYSMYCLLLXBTYXHBBZJKSSDMALXHYCFYGMQYPJYCQXJLLLJGSLZGQLYCJCCZOTYXMTMTTLLWTGPXYMZMKLPSZZZXHKQYSXCTYJZYHXSHYXZKXLZWPSQPYHJWPJPWXQQYLXSDHMRSLZZYZWTTCYXYSZZSHBSCCSTPLWSSCJCHNLCGCHSSPHYLHFHHXJSXYLLNYLSZDHZXYLSXLWZYKCLDYAXZCMDDYSPJTQJZLNWQPSSSWCTSTSZLBLNXSMNYYMJQBQHRZWTYYDCHQLXKPZWBGQYBKFCMZWPZLLYYLSZYDWHXPSBCMLJBSCGBHXLQHYRLJXYSWXWXZSLDFHLSLYNJLZYFLYJYCDRJLFSYZFSLLCQYQFGJYHYXZLYLMSTDJCYHBZLLNWLXXYGYYHSMGDHXXHHLZZJZXCZZZCYQZFNGWPYLCPKPYYPMCLQKDGXZGGWQBDXZZKZFBXXLZXJTPJPTTBYTSZZDWSLCHZHSLTYXHQLHYXXXYYZYSWTXZKHLXZXZPYHGCHKCFSYHUTJRLXFJXPTZTWHPLYXFCRHXSHXKYXXYHZQDXQWULHYHMJTBFLKHTXCWHJFWJCFPQRYQXCYYYQYGRPYWSGSUNGWCHKZDXYFLXXHJJBYZWTSXXNCYJJYMSWZJQRMHXZWFQSYLZJZGBHYNSLBGTTCSYBYXXWXYHXYYXNSQYXMQYWRGYQLXBBZLJSYLPSYTJZYHYZAWLRORJMKSCZJXXXYXCHDYXRYXXJDTSQFXLYLTSFFYXLMTYJMJUYYYXLTZCSXQZQHZXLYYXZHDNBRXXXJCTYHLBRLMBRLLAXKYLLLJLYXXLYCRYLCJTGJCMTLZLLCYZZPZPCYAWHJJFYBDYYZSMPCKZDQYQPBPCJPDCYZMDPBCYYDYCNNPLMTMLRMFMMGWYZBSJGYGSMZQQQZTXMKQWGXLLPJGZBQCDJJJFPKJKCXBLJMSWMDTQJXLDLPPBXCWRCQFBFQJCZAHZGMYKPHYYHZYKNDKZMBPJYXPXYHLFPNYYGXJDBKXNXHJMZJXSTRSTLDXSKZYSYBZXJLXYSLBZYSLHXJPFXPQNBYLLJQKYGZMCYZZYMCCSLCLHZFWFWYXZMWSXTYNXJHPYYMCYSPMHYSMYDYSHQYZCHMJJMZCAAGCFJBBHPLYZYLXXSDJGXDHKXXTXXNBHRMLYJSLTXMRHNLXQJXYZLLYSWQGDLBJHDCGJYQYCMHWFMJYBMBYJYJWYMDPWHXQLDYGPDFXXBCGJSPCKRSSYZJMSLBZZJFLJJJLGXZGYXYXLSZQYXBEXYXHGCXBPLDYHWETTWWCJMBTXCHXYQXLLXFLYXLLJLSSFWDPZSMYJCLMWYTCZPCHQEKCQBWLCQYDPLQPPQZQFJQDJHYMMCXTXDRMJWRHXCJZYLQXDYYNHYYHRSLSRSYWWZJYMTLTLLGTQCJZYABTCKZCJYCCQLJZQXALMZYHYWLWDXZXQDLLQSHGPJFJLJHJABCQZDJGTKHSSTCYJLPSWZLXZXRWGLDLZRLZXTGSLLLLZLYXXWGDZYGBDPHZPBRLWSXQBPFDWOFMWHLYPCBJCCLDMBZPBZZLCYQXLDOMZBLZWPDWYYGDSTTHCSQSCCRSSSYSLFYBFNTYJSZDFNDPDHDZZMBBLSLCMYFFGTJJQWFTMTPJWFNLBZCMMJTGBDZLQLPYFHYYMJYLSDCHDZJWJCCTLJCLDTLJJCPDDSQDSSZYBNDBJLGGJZXSXNLYCYBJXQYCBYLZCFZPPGKCXZDZFZTJJFJSJXZBNZYJQTTYJYHTYCZHYMDJXTTMPXSPLZCDWSLSHXYPZGTFMLCJTYCBPMGDKWYCYZCDSZZYHFLYCTYGWHKJYYLSJCXGYWJCBLLCSNDDBTZBSCLYZCZZSSQDLLMQYYHFSLQLLXFTYHABXGWNYWYYPLLSDLDLLBJCYXJZMLHLJDXYYQYTDLLLBUGBFDFBBQJZZMDPJHGCLGMJJPGAEHHBWCQXAXHHHZCHXYPHJAXHLPHJPGPZJQCQZGJJZZUZDMQYYBZZPHYHYBWHAZYJHYKFGDPFQSDLZMLJXKXGALXZDAGLMDGXMWZQYXXDXXPFDMMSSYMPFMDMMKXKSYZYSHDZKXSYSMMZZZMSYDNZZCZXFPLSTMZDNMXCKJMZTYYMZMZZMSXHHDCZJEMXXKLJSTLWLSQLYJZLLZJSSDPPMHNLZJCZYHMXXHGZCJMDHXTKGRMXFWMCGMWKDTKSXQMMMFZZYDKMSCLCMPCGMHSPXQPZDSSLCXKYXTWLWJYAHZJGZQMCSNXYYMMPMLKJXMHLMLQMXCTKZMJQYSZJSYSZHSYJZJCDAJZYBSDQJZGWZQQXFKDMSDJLFWEHKZQKJPEYPZYSZCDWYJFFMZZYLTTDZZEFMZLBNPPLPLPEPSZALLTYLKCKQZKGENQLWAGYXYDPXLHSXQQWQCQXQCLHYXXMLYCCWLYMQYSKGCHLCJNSZKPYZKCQZQLJPDMDZHLASXLBYDWQLWDNBQCRYDDZTJYBKBWSZDXDTNPJDTCTQDFXQQMGNXECLTTBKPWSLCTYQLPWYZZKLPYGZCQQPLLKCCYLPQMZCZQCLJSLQZDJXLDDHPZQDLJJXZQDXYZQKZLJCYQDYJPPYPQYKJYRMPCBYMCXKLLZLLFQPYLLLMBSGLCYSSLRSYSQTMXYXZQZFDZUYSYZTFFMZZSMZQHZSSCCMLYXWTPZGXZJGZGSJSGKDDHTQGGZLLBJDZLCBCHYXYZHZFYWXYZYMSDBZZYJGTSMTFXQYXQSTDGSLNXDLRYZZLRYYLXQHTXSRTZNGZXBNQQZFMYKMZJBZYMKBPNLYZPBLMCNQYZZZSJZHJCTZKHYZZJRDYZHNPXGLFZTLKGJTCTSSYLLGZRZBBQZZKLPKLCZYSSUYXBJFPNJZZXCDWXZYJXZZDJJKGGRSRJKMSMZJLSJYWQSKYHQJSXPJZZZLSNSHRNYPZTWCHKLPSRZLZXYJQXQKYSJYCZTLQZYBBYBWZPQDWWYZCYTJCJXCKCWDKKZXSGKDZXWWYYJQYYTCYTDLLXWKCZKKLCCLZCQQDZLQLCSFQCHQHSFSMQZZLNBJJZBSJHTSZDYSJQJPDLZCDCWJKJZZLPYCGMZWDJJBSJQZSYZYHHXJPBJYDSSXDZNCGLQMBTSFSBPDZDLZNFGFJGFSMPXJQLMBLGQCYYXBQKDJJQYRFKZTJDHCZKLBSDZCFJTPLLJGXHYXZCSSZZXSTJYGKGCKGYOQXJPLZPBPGTGYJZGHZQZZLBJLSQFZGKQQJZGYCZBZQTLDXRJXBSXXPZXHYZYCLWDXJJHXMFDZPFZHQHQMQGKSLYHTYCGFRZGNQXCLPDLBZCSCZQLLJBLHBZCYPZZPPDYMZZSGYHCKCPZJGSLJLNSCDSLDLXBMSTLDDFJMKDJDHZLZXLSZQPQPGJLLYBDSZGQLBZLSLKYYHZTTNTJYQTZZPSZQZTLLJTYYLLQLLQYZQLBDZLSLYYZYMDFSZSNHLXZNCZQZPBWSKRFBSYZMTHBLGJPMCZZLSTLXSHTCSYZLZBLFEQHLXFLCJLYLJQCBZLZJHHSSTBRMHXZHJZCLXFNBGXGTQJCZTMSFZKJMSSNXLJKBHSJXNTNLZDNTLMSJXGZJYJCZXYJYJWRWWQNZTNFJSZPZSHZJFYRDJSFSZJZBJFZQZZHZLXFYSBZQLZSGYFTZDCSZXZJBQMSZKJRHYJZCKMJKHCHGTXKXQGLXPXFXTRTYLXJXHDTSJXHJZJXZWZLCQSBTXWXGXTXXHXFTSDKFJHZYJFJXRZSDLLLTQSQQZQWZXSYQTWGWBZCGZLLYZBCLMQQTZHZXZXLJFRMYZFLXYSQXXJKXRMQDZDMMYYBSQBHGZMWFWXGMXLZPYYTGZYCCDXYZXYWGSYJYZNBHPZJSQSYXSXRTFYZGRHZTXSZZTHCBFCLSYXZLZQMZLMPLMXZJXSFLBYZMYQHXJSXRXSQZZZSSLYFRCZJRCRXHHZXQYDYHXSJJHZCXZBTYNSYSXJBQLPXZQPYMLXZKYXLXCJLCYSXXZZLXDLLLJJYHZXGYJWKJRWYHCPSGNRZLFZWFZZNSXGXFLZSXZZZBFCSYJDBRJKRDHHGXJLJJTGXJXXSTJTJXLYXQFCSGSWMSBCTLQZZWLZZKXJMLTMJYHSDDBXGZHDLBMYJFRZFSGCLYJBPMLYSMSXLSZJQQHJZFXGFQFQBPXZGYYQXGZTCQWYLTLGWSGWHRLFSFGZJMGMGBGTJFSYZZGZYZAFLSSPMLPFLCWBJZCLJJMZLPJJLYMQDMYYYFBGYGYZMLYZDXQYXRQQQHSYYYQXYLJTYXFSFSLLGNQCYHYCWFHCCCFXPYLYPLLZYXXXXXKQHHXSHJZCFZSCZJXCPZWHHHHHAPYLQALPQAFYHXDYLUKMZQGGGDDESRNNZLTZGCHYPPYSQJJHCLLJTOLNJPZLJLHYMHEYDYDSQYCDDHGZUNDZCLZYZLLZNTNYZGSLHSLPJJBDGWXPCDUTJCKLKCLWKLLCASSTKZZDNQNTTLYYZSSYSSZZRYLJQKCQDHHCRXRZYDGRGCWCGZQFFFPPJFZYNAKRGYWYQPQXXFKJTSZZXSWZDDFBBXTBGTZKZNPZZPZXZPJSZBMQHKCYXYLDKLJNYPKYGHGDZJXXEAHPNZKZTZCMXCXMMJXNKSZQNMNLWBWWXJKYHCPSTMCSQTZJYXTPCTPDTNNPGLLLZSJLSPBLPLQHDTNJNLYYRSZFFJFQWDPHZDWMRZCCLODAXNSSNYZRESTYJWJYJDBCFXNMWTTBYLWSTSZGYBLJPXGLBOCLHPCBJLTMXZLJYLZXCLTPNCLCKXTPZJSWCYXSFYSZDKNTLBYJCYJLLSTGQCBXRYZXBXKLYLHZLQZLNZCXWJZLJZJNCJHXMNZZGJZZXTZJXYCYYCXXJYYXJJXSSSJSTSSTTPPGQTCSXWZDCSYFPTFBFHFBBLZJCLZZDBXGCXLQPXKFZFLSYLTUWBMQJHSZBMDDBCYSCCLDXYCDDQLYJJWMQLLCSGLJJSYFPYYCCYLTJANTJJPWYCMMGQYYSXDXQMZHSZXPFTWWZQSWQRFKJLZJQQYFBRXJHHFWJJZYQAZMYFRHCYYBYQWLPEXCCZSTYRLTTDMQLYKMBBGMYYJPRKZNPBSXYXBHYZDJDNGHPMFSGMWFZMFQMMBCMZZCJJLCNUXYQLMLRYGQZCYXZLWJGCJCGGMCJNFYZZJHYCPRRCMTZQZXHFQGTJXCCJEAQCRJYHPLQLSZDJRBCQHQDYRHYLYXJSYMHZYDWLDFRYHBPYDTSSCNWBXGLPZMLZZTQSSCPJMXXYCSJYTYCGHYCJWYRXXLFEMWJNMKLLSWTXHYYYNCMMCWJDQDJZGLLJWJRKHPZGGFLCCSCZMCBLTBHBQJXQDSPDJZZGKGLFQYWBZYZJLTSTDHQHCTCBCHFLQMPWDSHYYTQWCNZZJTLBYMBPDYYYXSQKXWYYFLXXNCWCXYPMAELYKKJMZZZBRXYYQJFLJPFHHHYTZZXSGQQMHSPGDZQWBWPJHZJDYSCQWZKTXXSQLZYYMYSDZGRXCKKUJLWPYSYSCSYZLRMLQSYLJXBCXTLWDQZPCYCYKPPPNSXFYZJJRCEMHSZMSXLXGLRWGCSTLRSXBZGBZGZTCPLUJLSLYLYMTXMTZPALZXPXJTJWTCYYZLBLXBZLQMYLXPGHDSLSSDMXMBDZZSXWHAMLCZCPJMCNHJYSNSYGCHSKQMZZQDLLKABLWJXSFMOCDXJRRLYQZKJMYBYQLYHETFJZFRFKSRYXFJTWDSXXSYSQJYSLYXWJHSNLXYYXHBHAWHHJZXWMYLJCSSLKYDZTXBZSYFDXGXZJKHSXXYBSSXDPYNZWRPTQZCZENYGCXQFJYKJBZMLJCMQQXUOXSLYXXLYLLJDZBTYMHPFSTTQQWLHOKYBLZZALZXQLHZWRRQHLSTMYPYXJJXMQSJFNBXYXYJXXYQYLTHYLQYFMLKLJTMLLHSZWKZHLJMLHLJKLJSTLQXYLMBHHLNLZXQJHXCFXXLHYHJJGBYZZKBXSCQDJQDSUJZYYHZHHMGSXCSYMXFEBCQWWRBPYYJQTYZCYQYQQZYHMWFFHGZFRJFCDPXNTQYZPDYKHJLFRZXPPXZDBBGZQSTLGDGYLCQMLCHHMFYWLZYXKJLYPQHSYWMQQGQZMLZJNSQXJQSYJYCBEHSXFSZPXZWFLLBCYYJDYTDTHWZSFJMQQYJLMQXXLLDTTKHHYBFPWTYYSQQWNQWLGWDEBZWCMYGCULKJXTMXMYJSXHYBRWFYMWFRXYQMXYSZTZZTFYKMLDHQDXWYYNLCRYJBLPSXCXYWLSPRRJWXHQYPHTYDNXHHMMYWYTZCSQMTSSCCDALWZTCPQPYJLLQZYJSWXMZZMMYLMXCLMXCZMXMZSQTZPPQQBLPGXQZHFLJJHYTJSRXWZXSCCDLXTYJDCQJXSLQYCLZXLZZXMXQRJMHRHZJBHMFLJLMLCLQNLDXZLLLPYPSYJYSXCQQDCMQJZZXHNPNXZMEKMXHYKYQLXSXTXJYYHWDCWDZHQYYBGYBCYSCFGPSJNZDYZZJZXRZRQJJYMCANYRJTLDPPYZBSTJKXXZYPFDWFGZZRPYMTNGXZQBYXNBUFNQKRJQZMJEGRZGYCLKXZDSKKNSXKCLJSPJYYZLQQJYBZSSQLLLKJXTBKTYLCCDDBLSPPFYLGYDTZJYQGGKQTTFZXBDKTYYHYBBFYTYYBCLPDYTGDHRYRNJSPTCSNYJQHKLLLZSLYDXXWBCJQSPXBPJZJCJDZFFXXBRMLAZHCSNDLBJDSZBLPRZTSWSBXBCLLXXLZDJZSJPYLYXXYFTFFFBHJJXGBYXJPMMMPSSJZJMTLYZJXSWXTYLEDQPJMYGQZJGDJLQJWJQLLSJGJGYGMSCLJJXDTYGJQJQJCJZCJGDZZSXQGSJGGCXHQXSNQLZZBXHSGZXCXYLJXYXYYDFQQJHJFXDHCTXJYRXYSQTJXYEFYYSSYYJXNCYZXFXMSYSZXYYSCHSHXZZZGZZZGFJDLTYLNPZGYJYZYYQZPBXQBDZTZCZYXXYHHSQXSHDHGQHJHGYWSZTMZMLHYXGEBTYLZKQWYTJZRCLEKYSTDBCYKQQSAYXCJXWWGSBHJYZYDHCSJKQCXSWXFLTYNYZPZCCZJQTZWJQDZZZQZLJJXLSBHPYXXPSXSHHEZTXFPTLQYZZXHYTXNCFZYYHXGNXMYWXTZSJPTHHGYMXMXQZXTSBCZYJYXXTYYZYPCQLMMSZMJZZLLZXGXZAAJZYXJMZXWDXZSXZDZXLEYJJZQBHZWZZZQTZPSXZTDSXJJJZNYAZPHXYYSRNQDTHZHYYKYJHDZXZLSWCLYBZYECWCYCRYLCXNHZYDZYDYJDFRJJHTRSQTXYXJRJHOJYNXELXSFSFJZGHPZSXZSZDZCQZBYYKLSGSJHCZSHDGQGXYZGXCHXZJWYQWGYHKSSEQZZNDZFKWYSSTCLZSTSYMCDHJXXYWEYXCZAYDMPXMDSXYBSQMJMZJMTZQLPJYQZCGQHXJHHLXXHLHDLDJQCLDWBSXFZZYYSCHTYTYYBHECXHYKGJPXHHYZJFXHWHBDZFYZBCAPNPGNYDMSXHMMMMAMYNBYJTMPXYYMCTHJBZYFCGTYHWPHFTWZZEZSBZEGPFMTSKFTYCMHFLLHGPZJXZJGZJYXZSBBQSCZZLZCCSTPGXMJSFTCCZJZDJXCYBZLFCJSYZFGSZLYBCWZZBYZDZYPSWYJZXZBDSYUXLZZBZFYGCZXBZHZFTPBGZGEJBSTGKDMFHYZZJHZLLZZGJQZLSFDJSSCBZGPDLFZFZSZYZYZSYGCXSNXXCHCZXTZZLJFZGQSQYXZJQDCCZTQCDXZJYQJQCHXZTDLGSCXZSYQJQTZWLQDQZTQCHQQJZYEZZZPBWKDJFCJPZTYPQYQTTYNLMBDKTJZPQZQZZFPZSBNJLGYJDXJDZZKZGQKXDLPZJTCJDQBXDJQJSTCKNXBXZMSLYJCQMTJQWWCJQNJNLLLHJCWQTBZQYDZCZPZZDZYDDCYZZZCCJTTJFZDPRRTZTJDCQTQZDTJNPLZBCLLCTZSXKJZQZPZLBZRBTJDCXFCZDBCCJJLTQQPLDCGZDBBZJCQDCJWYNLLZYZCCDWLLXWZLXRXNTQQCZXKQLSGDFQTDDGLRLAJJTKUYMKQLLTZYTDYYCZGJWYXDXFRSKSTQTENQMRKQZHHQKDLDAZFKYPBGGPZREBZZYKZZSPEGJXGYKQZZZSLYSYYYZWFQZYLZZLZHWCHKYPQGNPGBLPLRRJYXCCSYYHSFZFYBZYYTGZXYLXCZWXXZJZBLFFLGSKHYJZEYJHLPLLLLCZGXDRZELRHGKLZZYHZLYQSZZJZQLJZFLNBHGWLCZCFJYSPYXZLZLXGCCPZBLLCYBBBBUBBCBPCRNNZCZYRBFSRLDCGQYYQXYGMQZWTZYTYJXYFWTEHZZJYWLCCNTZYJJZDEDPZDZTSYQJHDYMBJNYJZLXTSSTPHNDJXXBYXQTZQDDTJTDYYTGWSCSZQFLSHLGLBCZPHDLYZJYCKWTYTYLBNYTSDSYCCTYSZYYEBHEXHQDTWNYGYCLXTSZYSTQMYGZAZCCSZZDSLZCLZRQXYYELJSBYMXSXZTEMBBLLYYLLYTDQYSHYMRQWKFKBFXNXSBYCHXBWJYHTQBPBSBWDZYLKGZSKYHXQZJXHXJXGNLJKZLYYCDXLFYFGHLJGJYBXQLYBXQPQGZTZPLNCYPXDJYQYDYMRBESJYYHKXXSTMXRCZZYWXYQYBMCLLYZHQYZWQXDBXBZWZMSLPDMYSKFMZKLZCYQYCZLQXFZZYDQZPZYGYJYZMZXDZFYFYTTQTZHGSPCZMLCCYTZXJCYTJMKSLPZHYSNZLLYTPZCTZZCKTXDHXXTQCYFKSMQCCYYAZHTJPCYLZLYJBJXTPNYLJYYNRXSYLMMNXJSMYBCSYSYLZYLXJJQYLDZLPQBFZZBLFNDXQKCZFYWHGQMRDSXYCYTXNQQJZYYPFZXDYZFPRXEJDGYQBXRCNFYYQPGHYJDYZXGRHTKYLNWDZNTSMPKLBTHBPYSZBZTJZSZZJTYYXZPHSSZZBZCZPTQFZMYFLYPYBBJQXZMXXDJMTSYSKKBJZXHJCKLPSMKYJZCXTMLJYXRZZQSLXXQPYZXMKYXXXJCLJPRMYYGADYSKQLSNDHYZKQXZYZTCGHZTLMLWZYBWSYCTBHJHJFCWZTXWYTKZLXQSHLYJZJXTMPLPYCGLTBZZTLZJCYJGDTCLKLPLLQPJMZPAPXYZLKKTKDZCZZBNZDYDYQZJYJGMCTXLTGXSZLMLHBGLKFWNWZHDXUHLFMKYSLGXDTWWFRJEJZTZHYDXYKSHWFZCQSHKTMQQHTZHYMJDJSKHXZJZBZZXYMPAGQMSTPXLSKLZYNWRTSQLSZBPSPSGZWYHTLKSSSWHZZLYYTNXJGMJSZSUFWNLSOZTXGXLSAMMLBWLDSZYLAKQCQCTMYCFJBSLXCLZZCLXXKSBZQCLHJPSQPLSXXCKSLNHPSFQQYTXYJZLQLDXZQJZDYYDJNZPTUZDSKJFSLJHYLZSQZLBTXYDGTQFDBYAZXDZHZJNHHQBYKNXJJQCZMLLJZKSPLDYCLBBLXKLELXJLBQYCXJXGCNLCQPLZLZYJTZLJGYZDZPLTQCSXFDMNYCXGBTJDCZNBGBQYQJWGKFHTNPYQZQGBKPBBYZMTJDYTBLSQMPSXTBNPDXKLEMYYCJYNZCTLDYKZZXDDXHQSHDGMZSJYCCTAYRZLPYLTLKXSLZCGGEXCLFXLKJRTLQJAQZNCMBYDKKCXGLCZJZXJHPTDJJMZQYKQSECQZDSHHADMLZFMMZBGNTJNNLGBYJBRBTMLBYJDZXLCJLPLDLPCQDHLXZLYCBLCXZZJADJLNZMMSSSMYBHBSQKBHRSXXJMXSDZNZPXLGBRHWGGFCXGMSKLLTSJYYCQLTSKYWYYHYWXBXQYWPYWYKQLSQPTNTKHQCWDQKTWPXXHCPTHTWUMSSYHBWCRWXHJMKMZNGWTMLKFGHKJYLSYYCXWHYECLQHKQHTTQKHFZLDXQWYZYYDESBPKYRZPJFYYZJCEQDZZDLATZBBFJLLCXDLMJSSXEGYGSJQXCWBXSSZPDYZCXDNYXPPZYDLYJCZPLTXLSXYZYRXCYYYDYLWWNZSAHJSYQYHGYWWAXTJZDAXYSRLTDPSSYYFNEJDXYZHLXLLLZQZSJNYQYQQXYJGHZGZCYJCHZLYCDSHWSHJZYJXCLLNXZJJYYXNFXMWFPYLCYLLABWDDHWDXJMCXZTZPMLQZHSFHZYNZTLLDYWLSLXHYMMYLMBWWKYXYADTXYLLDJPYBPWUXJMWMLLSAFDLLYFLBHHHBQQLTZJCQJLDJTFFKMMMBYTHYGDCQRDDWRQJXNBYSNWZDBYYTBJHPYBYTTJXAAHGQDQTMYSTQXKBTZPKJLZRBEQQSSMJJBDJOTGTBXPGBKTLHQXJJJCTHXQDWJLWRFWQGWSHCKRYSWGFTGYGBXSDWDWRFHWYTJJXXXJYZYSLPYYYPAYXHYDQKXSHXYXGSKQHYWFDDDPPLCJLQQEEWXKSYYKDYPLTJTHKJLTCYYHHJTTPLTZZCDLTHQKZXQYSTEEYWYYZYXXYYSTTJKLLPZMCYHQGXYHSRMBXPLLNQYDQHXSXXWGDQBSHYLLPJJJTHYJKYPPTHYYKTYEZYENMDSHLCRPQFDGFXZPSFTLJXXJBSWYYSKSFLXLPPLBBBLBSFXFYZBSJSSYLPBBFFFFSSCJDSTZSXZRYYSYFFSYZYZBJTBCTSBSDHRTJJBYTCXYJEYLXCBNEBJDSYXYKGSJZBXBYTFZWGENYHHTHZHHXFWGCSTBGXKLSXYWMTMBYXJSTZSCDYQRCYTWXZFHMYMCXLZNSDJTTTXRYCFYJSBSDYERXJLJXBBDEYNJGHXGCKGSCYMBLXJMSZNSKGXFBNBPTHFJAAFXYXFPXMYPQDTZCXZZPXRSYWZDLYBBKTYQPQJPZYPZJZNJPZJLZZFYSBTTSLMPTZRTDXQSJEHBZYLZDHLJSQMLHTXTJECXSLZZSPKTLZKQQYFSYGYWPCPQFHQHYTQXZKRSGTTSQCZLPTXCDYYZXSQZSLXLZMYCPCQBZYXHBSXLZDLTCDXTYLZJYYZPZYZLTXJSJXHLPMYTXCQRBLZSSFJZZTNJYTXMYJHLHPPLCYXQJQQKZZSCPZKSWALQSBLCCZJSXGWWWYGYKTJBBZTDKHXHKGTGPBKQYSLPXPJCKBMLLXDZSTBKLGGQKQLSBKKTFXRMDKBFTPZFRTBBRFERQGXYJPZSSTLBZTPSZQZSJDHLJQLZBPMSMMSXLQQNHKNBLRDDNXXDHDDJCYYGYLXGZLXSYGMQQGKHBPMXYXLYTQWLWGCPBMQXCYZYDRJBHTDJYHQSHTMJSBYPLWHLZFFNYPMHXXHPLTBQPFBJWQDBYGPNZTPFZJGSDDTQSHZEAWZZYLLTYYBWJKXXGHLFKXDJTMSZSQYNZGGSWQSPHTLSSKMCLZXYSZQZXNCJDQGZDLFNYKLJCJLLZLMZZNHYDSSHTHZZLZZBBHQZWWYCRZHLYQQJBEYFXXXWHSRXWQHWPSLMSSKZTTYGYQQWRSLALHMJTQJSMXQBJJZJXZYZKXBYQXBJXSHZTSFJLXMXZXFGHKZSZGGYLCLSARJYHSLLLMZXELGLXYDJYTLFBHBPNLYZFBBHPTGJKWETZHKJJXZXXGLLJLSTGSHJJYQLQZFKCGNNDJSSZFDBCTWWSEQFHQJBSAQTGYPQLBXBMMYWXGSLZHGLZGQYFLZBYFZJFRYSFMBYZHQGFWZSYFYJJPHZBYYZFFWODGRLMFTWLBZGYCQXCDJYGZYYYYTYTYDWEGAZYHXJLZYYHLRMGRXXZCLHNELJJTJTPWJYBJJBXJJTJTEEKHWSLJPLPSFYZPQQBDLQJJTYYQLYZKDKSQJYYQZLDQTGJQYZJSUCMRYQTHTEJMFCTYHYPKMHYZWJDQFHYYXWSHCTXRLJHQXHCCYYYJLTKTTYTMXGTCJTZAYYOCZLYLBSZYWJYTSJYHBYSHFJLYGJXXTMZYYLTXXYPZLXYJZYZYYPNHMYMDYYLBLHLSYYQQLLNJJYMSOYQBZGDLYXYLCQYXTSZEGXHZGLHWBLJHEYXTWQMAKBPQCGYSHHEGQCMWYYWLJYJHYYZLLJJYLHZYHMGSLJLJXCJJYCLYCJPCPZJZJMMYLCQLNQLJQJSXYJMLSZLJQLYCMMHCFMMFPQQMFYLQMCFFQMMMMHMZNFHHJGTTHHKHSLNCHHYQDXTMMQDCYZYXYQMYQYLTDCYYYZAZZCYMZYDLZFFFMMYCQZWZZMABTBYZTDMNZZGGDFTYPCGQYTTSSFFWFDTZQSSYSTWXJHXYTSXXYLBYQHWWKXHZXWZNNZZJZJJQJCCCHYYXBZXZCYZTLLCQXYNJYCYYCYNZZQYYYEWYCZDCJYCCHYJLBTZYYCQWMPWPYMLGKDLDLGKQQBGYCHJXY";
//此处收录了375个多音字
var oMultiDiff={"19969":"DZ","19975":"WM","19988":"QJ","20048":"YL","20056":"SC","20060":"NM","20094":"QG","20127":"QJ","20167":"QC","20193":"YG","20250":"KH","20256":"ZC","20282":"SC","20285":"QJG","20291":"TD","20314":"YD","20340":"NE","20375":"TD","20389":"YJ","20391":"CZ","20415":"PB","20446":"YS","20447":"SQ","20504":"TC","20608":"KG","20854":"QJ","20857":"ZC","20911":"PF","20504":"TC","20608":"KG","20854":"QJ","20857":"ZC","20911":"PF","20985":"AW","21032":"PB","21048":"XQ","21049":"SC","21089":"YS","21119":"JC","21242":"SB","21273":"SC","21305":"YP","21306":"QO","21330":"ZC","21333":"SDC","21345":"QK","21378":"CA","21397":"SC","21414":"XS","21442":"SC","21477":"JG","21480":"TD","21484":"ZS","21494":"YX","21505":"YX","21512":"HG","21523":"XH","21537":"PB","21542":"PF","21549":"KH","21571":"E","21574":"DA","21588":"TD","21589":"O","21618":"ZC","21621":"KHA","21632":"ZJ","21654":"KG","21679":"LKG","21683":"KH","21710":"A","21719":"YH","21734":"WOE","21769":"A","21780":"WN","21804":"XH","21834":"A","21899":"ZD","21903":"RN","21908":"WO","21939":"ZC","21956":"SA","21964":"YA","21970":"TD","22003":"A","22031":"JG","22040":"XS","22060":"ZC","22066":"ZC","22079":"MH","22129":"XJ","22179":"XA","22237":"NJ","22244":"TD","22280":"JQ","22300":"YH","22313":"XW","22331":"YQ","22343":"YJ","22351":"PH","22395":"DC","22412":"TD","22484":"PB","22500":"PB","22534":"ZD","22549":"DH","22561":"PB","22612":"TD","22771":"KQ","22831":"HB","22841":"JG","22855":"QJ","22865":"XQ","23013":"ML","23081":"WM","23487":"SX","23558":"QJ","23561":"YW","23586":"YW","23614":"YW","23615":"SN","23631":"PB","23646":"ZS","23663":"ZT","23673":"YG","23762":"TD","23769":"ZS","23780":"QJ","23884":"QK","24055":"XH","24113":"DC","24162":"ZC","24191":"GA","24273":"QJ","24324":"NL","24377":"TD","24378":"QJ","24439":"PF","24554":"ZS","24683":"TD","24694":"WE","24733":"LK","24925":"TN","25094":"ZG","25100":"XQ","25103":"XH","25153":"PB","25170":"PB","25179":"KG","25203":"PB","25240":"ZS","25282":"FB","25303":"NA","25324":"KG","25341":"ZY","25373":"WZ","25375":"XJ","25384":"A","25457":"A","25528":"SD","25530":"SC","25552":"TD","25774":"ZC","25874":"ZC","26044":"YW","26080":"WM","26292":"PB","26333":"PB","26355":"ZY","26366":"CZ","26397":"ZC","26399":"QJ","26415":"ZS","26451":"SB","26526":"ZC","26552":"JG","26561":"TD","26588":"JG","26597":"CZ","26629":"ZS","26638":"YL","26646":"XQ","26653":"KG","26657":"XJ","26727":"HG","26894":"ZC","26937":"ZS","26946":"ZC","26999":"KJ","27099":"KJ","27449":"YQ","27481":"XS","27542":"ZS","27663":"ZS","27748":"TS","27784":"SC","27788":"ZD","27795":"TD","27812":"O","27850":"PB","27852":"MB","27895":"SL","27898":"PL","27973":"QJ","27981":"KH","27986":"HX","27994":"XJ","28044":"YC","28065":"WG","28177":"SM","28267":"QJ","28291":"KH","28337":"ZQ","28463":"TL","28548":"DC","28601":"TD","28689":"PB","28805":"JG","28820":"QG","28846":"PB","28952":"TD","28975":"ZC","29100":"A","29325":"QJ","29575":"SL","29602":"FB","30010":"TD","30044":"CX","30058":"PF","30091":"YSP","30111":"YN","30229":"XJ","30427":"SC","30465":"SX","30631":"YQ","30655":"QJ","30684":"QJG","30707":"SD","30729":"XH","30796":"LG","30917":"PB","31074":"NM","31085":"JZ","31109":"SC","31181":"ZC","31192":"MLB","31293":"JQ","31400":"YX","31584":"YJ","31896":"ZN","31909":"ZY","31995":"XJ","32321":"PF","32327":"ZY","32418":"HG","32420":"XQ","32421":"HG","32438":"LG","32473":"GJ","32488":"TD","32521":"QJ","32527":"PB","32562":"ZSQ","32564":"JZ","32735":"ZD","32793":"PB","33071":"PF","33098":"XL","33100":"YA","33152":"PB","33261":"CX","33324":"BP","33333":"TD","33406":"YA","33426":"WM","33432":"PB","33445":"JG","33486":"ZN","33493":"TS","33507":"QJ","33540":"QJ","33544":"ZC","33564":"XQ","33617":"YT","33632":"QJ","33636":"XH","33637":"YX","33694":"WG","33705":"PF","33728":"YW","33882":"SR","34067":"WM","34074":"YW","34121":"QJ","34255":"ZC","34259":"XL","34425":"JH","34430":"XH","34485":"KH","34503":"YS","34532":"HG","34552":"XS","34558":"YE","34593":"ZL","34660":"YQ","34892":"XH","34928":"SC","34999":"QJ","35048":"PB","35059":"SC","35098":"ZC","35203":"TQ","35265":"JX","35299":"JX","35782":"SZ","35828":"YS","35830":"E","35843":"TD","35895":"YG","35977":"MH","36158":"JG","36228":"QJ","36426":"XQ","36466":"DC","36710":"JC","36711":"ZYG","36767":"PB","36866":"SK","36951":"YW","37034":"YX","37063":"XH","37218":"ZC","37325":"ZC","38063":"PB","38079":"TD","38085":"QY","38107":"DC","38116":"TD","38123":"YD","38224":"HG","38241":"XTC","38271":"ZC","38415":"YE","38426":"KH","38461":"YD","38463":"AE","38466":"PB","38477":"XJ","38518":"YT","38551":"WK","38585":"ZC","38704":"XS","38739":"LJ","38761":"GJ","38808":"SQ","39048":"JG","39049":"XJ","39052":"HG","39076":"CZ","39271":"XT","39534":"TD","39552":"TD","39584":"PB","39647":"SB","39730":"LG","39748":"TPB","40109":"ZQ","40479":"ND","40516":"HG","40536":"HG","40583":"QJ","40765":"YQ","40784":"QJ","40840":"YK","40863":"QJG"};
//参数,中文字符串
//返回值:拼音首字母串数组
function makePy(str){
	if(str=="") return;
	if(typeof(str) != "string")
		throw new Error(-1,"函数makePy需要字符串类型参数!");
	var arrResult = new Array(); //保存中间结果的数组
	for(var i=0,len=str.length;i<len;i++){
		//获得unicode码
		var ch = str.charAt(i);
		//检查该unicode码是否在处理范围之内,在则返回该码对映汉字的拼音首字母,不在则调用其它函数处理
		arrResult.push(checkCh(ch));
	}
	//处理arrResult,返回所有可能的拼音首字母串数组
	return mkRslt(arrResult);
}

function checkCh(ch){
	var uni = ch.charCodeAt(0);
	//如果不在汉字处理范围之内,返回原字符,也可以调用自己的处理函数
	if(uni > 40869 || uni < 19968)
	return ch; //dealWithOthers(ch);
	//检查是否是多音字,是按多音字处理,不是就直接在strChineseFirstPY字符串中找对应的首字母
	return (oMultiDiff[uni]?oMultiDiff[uni]:(strChineseFirstPY.charAt(uni-19968)));
}

function mkRslt(arr){
	var arrRslt = [""];
	for(var i=0,len=arr.length;i<len;i++){
	var str = arr[i];
	var strlen = str.length;
	if(strlen == 1){
	for(var k=0;k<arrRslt.length;k++){
	arrRslt[k] += str;
	}
	}else{
	var tmpArr = arrRslt.slice(0);
	arrRslt = [];
	for(k=0;k<strlen;k++){
	//复制一个相同的arrRslt
	var tmp = tmpArr.slice(0);
	//把当前字符str[k]添加到每个元素末尾
	for(var j=0;j<tmp.length;j++){
	tmp[j] += str.charAt(k);
	}
	//把复制并修改后的数组连接到arrRslt上
	arrRslt = arrRslt.concat(tmp);
	}
	}
	}
	return arrRslt;
}
//两端去空格函数
String.prototype.trim = function() {    
	return this.replace(/(^\s*)|(\s*$)/g,""); 
};

/**
 * 计算税率
 * amt1:含税金额
 * amt2：不含税金额
 */
function getTaxRate(amt1,amt2){
	var num1= new Number(reThousandFormat(amt1)).toFixed(2);
	var num2= new Number(reThousandFormat(amt2)).toFixed(2);
	if(num2==0){
		return 0;
	}
	return toNum((((num1-num2)/num2)*100).toFixed(2));
} 

/**
 * 计算税额
 * amt1:含税金额
 * rate：税率
 */
function getTaxAmountByRate(amt1,rate){
	var num1= toNum(reThousandFormat(amt1));
	var num2= toNum(reThousandFormat(rate));
	return toNum(num1-toNum((num1*100/(num2+100)).toFixed(2)));
}

/**
 * 计算税额
 * amt1:含税金额
 * amt2：不含税金额
 */
function getTaxAmountByNotax(amt1,amt2){
	var num1= toNum(reThousandFormat(amt1));
	var num2= toNum(reThousandFormat(amt2));
	return toNum((num1-num2).toFixed(2));
}

/**
 * 计算不含税金额
 * amt1:含税金额
 * rate：税率
 */
function getNoTaxAmount(amt1,rate){
	var num1= toNum(reThousandFormat(amt1));
	var num2= toNum(reThousandFormat(rate));
	return toNum((num1*100/(num2+100)).toFixed(2));
}

/**
 * 计算含税金额
 * amt1:不含税金额
 * rate：税率
 */
function getAmount(amt1,rate){
	var num1 = new Number(reThousandFormat(amt1)).toFixed(2); 
	var num2= new Number(reThousandFormat(rate)).toFixed(2);
	return toNum(((num1/(100-num2))*100).toFixed(2));
}

/**
 * 字符串转数字
 * @author kevin
 * 
 * @param value
 * @returns {Number}
 */
function toNum(value){
	return new Number(new Number(value).toFixed(2));
}

/**
 * 时间戳转成时间字符串（yyyy-MM-dd HH:mm）
 * @author kevin
 * 
 * @param timestamp
 * @returns
 */
function onTimestampToDateStr(timestamp) {
	var d = new Date(timestamp);
	var month = d.getMonth() + 1;
	var day = d.getDate();
	var hour = d.getHours();
	var minute = d.getMinutes();
	if (month >= 1 && month <= 9) {
		month = "0" + month;
	}
	if (day >= 0 && day <= 9) {
		day = "0" + day;
	}
	if (hour >= 0 && hour <= 9) {
		hour = "0" + hour;
	}
	if (minute >= 0 && minute <= 9) {
		minute = "0" + minute;
	}
	return (d.getFullYear()) + "-" + month + "-" + day + " " + hour + ":" + minute;
}

/**
 * 关闭弹窗
 * @author kevin
 * 
 * @param action
 * @returns
 */
function CloseWindow(action) {
	if (window.CloseOwnerWindow) {
		return window.CloseOwnerWindow(action);
	}else{
		window.close();
	}
}

/**
 * 验证手机号码
 * @author kevin
 * 
 * @param mobilephone
 * @returns
 */
function isMobile(mobilephone) {
	if (!(/^(((13[0-9]{1})|(15[0-9]{1})|(17[0-9]{1})|(18[0-9]{1}))+\d{8})$/.test(mobilephone))) {
		return false;
	} else {
		return true;
	}
}

/**
 * 获取url参数
 * @author kevin
 * 
 * @param name
 * @returns
 */
function getQueryString(name) {
    var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)", "i");
    var r = window.location.search.substr(1).match(reg);
    if (r != null) return unescape(r[2]);
    return null;
}

/**
 * 转换商会职务（江北区总商会职务、其他商会职务）
 * @author kevin
 * 
 * @param shzwlb
 * @returns
 */
function covertShzwlb(shzwlb) {
	var shzwlb_text = "";
	if(shzwlb == "JBQZSHZW-01"){
		shzwlb_text = "主席";
	}else if(shzwlb == "JBQZSHZW-02"){
		shzwlb_text = "党组书记";
	}else if(shzwlb == "JBQZSHZW-03"){
		shzwlb_text = "副书记";
	}else if(shzwlb == "JBQZSHZW-04"){
		shzwlb_text = "副会长";
	}else if(shzwlb == "JBQZSHZW-05"){
		shzwlb_text = "常委";
	}else if(shzwlb == "JBQZSHZW-06"){
		shzwlb_text = "执委";
	}else if(shzwlb == "JBQZSHZW-07"){
		shzwlb_text = "会员";
	}else if(shzwlb == "QTSHZW-01"){
		shzwlb_text = "会长";
	}else if(shzwlb == "QTSHZW-02"){
		shzwlb_text = "秘书长";
	}else if(shzwlb == "QTSHZW-03"){
		shzwlb_text = "常务副会长";
	}else if(shzwlb == "QTSHZW-04"){
		shzwlb_text = "副会长";
	}else if(shzwlb == "QTSHZW-05"){
		shzwlb_text = "常务理事";
	}else if(shzwlb == "QTSHZW-06"){
		shzwlb_text = "理事";
	}else if(shzwlb == "QTSHZW-07"){
		shzwlb_text = "会员";
	}
    return shzwlb_text;
}

/**
 * 转换主要荣誉类别
 * @author kevin
 * 
 * @param zyrylb
 * @returns
 */
function covertZyrylb(zyrylb) {
	var zyrylb_text = "";
	if(zyrylb == "ZYRY-01"){
		zyrylb_text = "劳动模范";
	}else if(zyrylb == "ZYRY-02"){
		zyrylb_text = "五一奖章";
	}else if(zyrylb == "ZYRY-03"){
		zyrylb_text = "三八红旗手";
	}else if(zyrylb == "ZYRY-04"){
		zyrylb_text = "五四奖章";
	}else if(zyrylb == "ZYRY-05"){
		zyrylb_text = "优秀社会主义建设者";
	}else if(zyrylb == "ZYRY-06"){
		zyrylb_text = "光彩事业奖章";
	}else if(zyrylb == "ZYRY-07"){
		zyrylb_text = "光彩事业国土绿化贡献奖";
	}else if(zyrylb == "ZYRY-08"){
		zyrylb_text = "优秀企业";
	}
    return zyrylb_text;
}

/**
 * 转换资料失败类别
 * @author kevin
 * 
 * @param infolb
 * @returns
 */
function covertFailInfolb(infolb) {
	var infolb_text = "";
	if(infolb == "HYSPZL-01"){
		infolb_text = "基本信息";
	}else if(infolb == "HYSPZL-02"){
		infolb_text = "商会职务";
	}else if(infolb == "HYSPZL-03"){
		infolb_text = "主要荣誉";
	}else if(infolb == "HYSPZL-04"){
		infolb_text = "法人资料";
	}else if(infolb == "HYSPZL-05"){
		infolb_text = "授奖情况";
	}else if(infolb == "HYSPZL-06"){
		infolb_text = "企业介绍";
	}else if(infolb == "HYSPZL-07"){
		infolb_text = "社团介绍";
	}else if(infolb == "HYSPZL-08"){
		infolb_text = "证件资料";
	}
    return infolb_text;
}
//记住密码
function setCookie(key,value) { //设置cookie    
	$.cookie(key, value,{expires: 7*1000*60*24,path:'/',secure: false});//调用jquery.cookie.js中的方法设置cookie中的用户名    
}
//获取cookie  
function getCookie(key) { //获取cookie    
	var value = $.cookie(key); //获取cookie中的用户名   
	return value;

}